name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/**/*.sh'
      - 'Dockerfile'
      - 'docker-compose.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/**/*.sh'
      - 'Dockerfile'
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  lint-bash:
    name: Lint Bash Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Run shellcheck on scripts
        run: find scripts -type f -name "*.sh" -exec shellcheck {} +

  build:
    name: Test Docker Compose Build
    runs-on: ubuntu-latest
    needs: lint-bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build
